// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTHgUy5og0R0DfATFqNVEFfFRmA63xPM',
    appId: '1:949303853336:web:16dc3564cd01264409de6d',
    messagingSenderId: '949303853336',
    projectId: 'chatup-d9d43',
    authDomain: 'chatup-d9d43.firebaseapp.com',
    storageBucket: 'chatup-d9d43.appspot.com',
    measurementId: 'G-VTRTGFM7ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFP3IzFZL6zxQHCteYADun5I2BS1npLio',
    appId: '1:949303853336:android:aa84b03ad11b10d109de6d',
    messagingSenderId: '949303853336',
    projectId: 'chatup-d9d43',
    storageBucket: 'chatup-d9d43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPDzP4fDklnhfjVq6ieQm_PP_RznHZiHw',
    appId: '1:949303853336:ios:851bf56593a63f7409de6d',
    messagingSenderId: '949303853336',
    projectId: 'chatup-d9d43',
    storageBucket: 'chatup-d9d43.appspot.com',
    iosClientId: '949303853336-genh1on5tlnn2bs756crensr0270jero.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
