// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwqZnxp8c0_Dw6k6QTQFXr7Y3HuyjpP38',
    appId: '1:279778724826:web:1f0f3b2d343d7fa8394ee3',
    messagingSenderId: '279778724826',
    projectId: 'instagram-tut-da314',
    authDomain: 'instagram-tut-da314.firebaseapp.com',
    storageBucket: 'instagram-tut-da314.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO074zoEq7fJ13kMhxNmYvBTYHpMA4PGo',
    appId: '1:279778724826:android:96ebe556c6917fa3394ee3',
    messagingSenderId: '279778724826',
    projectId: 'instagram-tut-da314',
    storageBucket: 'instagram-tut-da314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAix4xaeGkDgfIOgLynUIRa7uCz_q_2JuE',
    appId: '1:279778724826:ios:d40ac53cdf09586c394ee3',
    messagingSenderId: '279778724826',
    projectId: 'instagram-tut-da314',
    storageBucket: 'instagram-tut-da314.appspot.com',
    androidClientId: '279778724826-ugr4n48odbpu9mcfej42huccss5g5mfb.apps.googleusercontent.com',
    iosClientId: '279778724826-g0m9sn7jbnf1qlo76udhdgjej62m1e0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
